In [11]:
import pandas as pd
import requests

In [3]:
import chardet

with open('books.csv', 'rb') as f:
    result = chardet.detect(f.read(50000))  # analyze first 50KB
    print(result)

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

In [4]:
books = pd.read_csv('books.csv', encoding='ISO-8859-1', on_bad_lines="skip", sep=";")
print(list(books.columns))

['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M', 'Image-URL-L']

C:\Users\ROG STRIX G17\AppData\Local\Temp\ipykernel_235208\1513724949.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('books.csv', encoding='ISO-8859-1', on_bad_lines="skip", sep=";")

In [ ]:
books = books.drop(['Image-URL-S', 'Image-URL-M', 'ISBN', 'Publisher'], axis=1)

In [8]:
books = books.rename(columns={"Year-Of-Publication": "year", "Book-Author" : "author", "Book-Title" : "title"
                              ,"Image-URL-L" : "image"})
books.head()

,title,author,year,image
0,Classical Mythology,Mark P. O. Morford,2002,http://images.amazon.com/images/P/0195153448.0...
1,Clara Callan,Richard Bruce Wright,2001,http://images.amazon.com/images/P/0002005018.0...
2,Decision in Normandy,Carlo D'Este,1991,http://images.amazon.com/images/P/0060973129.0...
3,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,http://images.amazon.com/images/P/0374157065.0...
4,The Mummies of Urumchi,E. J. W. Barber,1999,http://images.amazon.com/images/P/0393045218.0...

In [9]:
books['description'] = ''
books.head()

,title,author,year,image,description
0,Classical Mythology,Mark P. O. Morford,2002,http://images.amazon.com/images/P/0195153448.0...,
1,Clara Callan,Richard Bruce Wright,2001,http://images.amazon.com/images/P/0002005018.0...,
2,Decision in Normandy,Carlo D'Este,1991,http://images.amazon.com/images/P/0060973129.0...,
3,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,http://images.amazon.com/images/P/0374157065.0...,
4,The Mummies of Urumchi,E. J. W. Barber,1999,http://images.amazon.com/images/P/0393045218.0...,

In [16]:
api = "https://www.googleapis.com/books/v1/volumes"

params = {
    "q" : f"intitle:L'Etranger",
    "maxResults": 1
}

response = requests.get(api, params=params)

response = response.json()

print(response["items"][0]["volumeInfo"]["description"])


descriptions = []
for title in books['title']:
    response = requests.get(api, params = {"q" : f"intitle:{title}", "maxResults" : 1})

    response = response.json()

    if "items" in response and "volumeInfo" in response["items"][0] and "description" in response["items"][0]["volumeInfo"]:
        
        description = response["items"][0]["volumeInfo"]["description"]
        print(description[0:10])

    else:
        description = ""
    
    descriptions.append(description)

books["description"] = descriptions

Titre:L'Étranger.Auteur: Albert Camus.Date de parution: 1942Est le premier roman d'Albert Camus, paru en 1942. Il prend place dans la tétralogie que Camus nommera « cycle de l'absurde » qui décrit les fondements de la philosophie camusienne : l'absurde. Cette tétralogie comprend également l'essai intitulé Le Mythe de Sisyphe ainsi que les pièces de théâtre Caligula et Le Malentendu. Le roman a été traduit en quarante langues et une adaptation cinématographique en a été réalisée par Luchino Visconti en 1967.
Classical
In a small
Here, for
Documents
With the s
A discussi
Examines t
David Adam
Hitler's S
Presents a
This lates
A famous a
This eye-o
The satiri
Provides a
Two twins,
Please not
How far wo
Our critic
In "Out of
A novel of
Im China d
In a Carme
Harper Lee
Murder vic
Austen's c
Mais où no
#1 NEW YOR
"English t
Filled wit
Foreign ex
A corporat
Willie Sta
Be inspire
An Italian
A step by
Ten short
À Lonesome
Set agains
In this se
"In his fi
While driv
“The Joy L
Generally
Story of T
One windy
Explains t
" Pollard
Mansfield'
In 1991, J
In trade p
Themes: Hi
With his f
Have you e
What's the
Ancient mo
The art of
Quayle foc
LEADERSHIP
The author
Tyrel and
In an effo
Spanish la
La última
NEW YORK T
What happe
Unlock the
Informativ
"Prepare t
In writer
Twenty of
What the r
"Original
McDonald's
Popular sp
The acclai
A heartwar
Plot Eddie
Missing in
Babylon 5
"Recoverin
Donated.
Explores t
The explos
Years afte
Lewis Griz
Allie Fox,
Lewis Griz
The true s
A frighten
After five
This encha
With his "
When Chris
"Elogiado
Now a Netf
Don't miss
The car fi
A professo
Offers a c
A story th
The New Yo
Il a connu
Nell Galla
«Cuando yo
El amor co
Story book
Published
Keep It Si
Amy, the q
When Nore
Cet ouvrag
Mystery no
Now reissu
Novelist D
A poignant
Adams's be
A successf
Are you lo
The origin
Jane, Eliz
After the
Qwilleran
This down-
No matter
The danger
The tranqu
Nearly sev
Die Geschi
Jacqueline
«Ein Wunde
Internatio
Battling a
En 1925, c
"Captivati
NATIONAL B
#1 New Yor
Medical ex
While spen
Shemaine O
Left desti
There is n
#1 NEW YOR
YA. Murder
From the b
The girls
Les plus b
The Master
The acknow
As Paul gr
History an
The Silent
Clifford g
Female med
Quand un s
Frank McCo
The explos
Le Crazy H
No author
THE NO. 1
Readers wi
The New Yo
On Valenti
The #1 New
"Under the
This shini
A poetic,
'Holy Wood
Discworld'
Some Pig T
※ Google P
Cohen the
Discworld
"A master
Murder and
On the Bri
Begun in 1
The Wind i
Bernard Co
Fantasy-ro
In this ne
This beaut
Through ma
Lyra and W
Pullman in
The spellb
The one-an
The tranqu
Arthur Mac
While rese
Tanuja Des
From the #
Little Wom
Jane Auste
This is a
Orphaned P
**NOW INCL
A collecti
Charles Di
Enid Blyto
A miscella
The League
Neil Gaima
C.1 GENERA
Dark Horse
Written by
A decade a
At the beg
#1 NEW YOR
Racial ten
A Riverhea
In the lat
Diane Rayo
Gordon is
When Delan
Deux Sympo
Discusses
The inspir
The Journe
Two sixtee
Heather re
The journa
Former lov
In Kansas,
An account
Escape on
"RELENTLES
Christophe
The Cahill
Includes t
Urn Burial
The latest
(Guitar Re
Douglas Ad
In a stark
Add Affini
Two of Lop
This book
The classi
From New Y
De levensg
Pocas vece
Judge Debo
When Peter
Trying to
Through ma
A fourteen
The discov
When the N
Jay is tra
When Mitch
How Irish
A suburban
From the P
THE STORY:
Darcy Gall
Arthur Den
A collecti
This "I Sp
Shopping f
From the s
Nero Wolfe
Now availa
A riveting
Short biog
The Jewish
Based on t
I was doin
For use in
A pilot st
Now, for t
An introdu
The book e
UNLOCK THE
What you'v
Tony Abram
The Fox is
Oxford Sch
FROM THE D
Marry Me..
Delve into
The Advent
Mary Crow
In this un
GIFT LOCAL
Sebold's m
CENTERTout
“A TOUR DE
From the a
This is a
Born in 18
In this fo
Reveals th
Camping is
Diva Mawrd
A memoir t
A breathta
Now in har
This edite
Reflexione
Ria y Mari
Britpop wa
A panorami
What does
V.1 A-E. -
Describes
หนังสือภาษ
Alice, who
Dor, heir
Jordon, on
At a time
This is on
Ellen Fran
When Mitch
At a fundr
Sometimes
﻿Philip Jo
This novel
In the two
Third-grad
In a parod
A horse in
Oliver Twi
Text and p
The monste
Hailed by
Fifteen-ye
It's not u
Sebold's m
When Delan
Marion Col
Helen Edmu
NATIONAL B
A novel ab
The sizzli
Called "st
WTF? Why t
In this Ne
Donation.
Combining
"The maste
Three firs
This enthr
Joshua ret
Sisters of
Will unbel
It’s a day
DIV"People
Who is Ted
Looks at t
#1 NEW YOR
Afterword
A bus driv
Always a l
Follows th
Sunshine S
In a suspe
Guy Bouche
One of the
Taylor Gre
Presents a
Vikram Set
Essays by
Cranford i
When Kings
In this my
"English t
During Wor
Richard Ju
Enriched C
A classic
Rich selec
This is a
Pel Dalton
This 30th
Begun in t
In this do
Octavio Pa
Here are 1
Struggling
Una donna
A guide to
Kohn argue
Describes
Explains t
After weas
After buyi
20ème anni
A stunning
Readers wh
Follows a
A mesmeriz
This symph
Rose Felle
In this US
In The Swe
This work
Grace McCa
When the l
A vacation
In the sil
Despite a
A successf
The New Yo
Cela fait
The Straw
This book

KeyboardInterrupt:

In [20]:

books.loc[:len(descriptions) - 1, "description"] = descriptions

In [24]:
books.head(50)

,title,author,year,image,description
0,Classical Mythology,Mark P. O. Morford,2002,http://images.amazon.com/images/P/0195153448.0...,"Classical Mythology, Sixth Edition, continues ..."
1,Clara Callan,Richard Bruce Wright,2001,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct..."
2,Decision in Normandy,Carlo D'Este,1991,http://images.amazon.com/images/P/0060973129.0...,"Here, for the first time in paperback, is an o..."
3,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,http://images.amazon.com/images/P/0374157065.0...,Documents the influenza epidemic of 1918 which...
4,The Mummies of Urumchi,E. J. W. Barber,1999,http://images.amazon.com/images/P/0393045218.0...,
5,The Kitchen God's Wife,Amy Tan,1991,http://images.amazon.com/images/P/0399135782.0...,With the same narrative skills and evocative p...
6,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,http://images.amazon.com/images/P/0425176428.0...,
7,PLEADING GUILTY,Scott Turow,1993,http://images.amazon.com/images/P/0671870432.0...,A discussion of the legal issues and court pro...
8,Under the Black Flag: The Romance and the Real...,David Cordingly,1996,http://images.amazon.com/images/P/0679425608.0...,Examines the popular image of pirates in moder...
9,Where You'll Find Me: And Other Stories,Ann Beattie,2002,http://images.amazon.com/images/P/074322678X.0...,
10,Nights Below Station Street,David Adams Richards,1988,http://images.amazon.com/images/P/0771074670.0...,David Adams Richards' Governor General's Award...
11,Hitler's Secret Bankers: The Myth of Swiss Neu...,Adam Lebor,2000,http://images.amazon.com/images/P/080652121X.0...,Hitler's Secret Bankers was the first book to ...
12,The Middle Stories,Sheila Heti,2004,http://images.amazon.com/images/P/0887841740.0...,Presents a collection of short stories that de...
13,Jane Doe,R. J. Kaiser,1999,http://images.amazon.com/images/P/1552041778.0...,
14,A Second Chicken Soup for the Woman's Soul (Ch...,Jack Canfield,1998,http://images.amazon.com/images/P/1558746218.0...,This latest collection of stories celebrates t...
15,The Witchfinder (Amos Walker Mystery Series),Loren D. Estleman,1998,http://images.amazon.com/images/P/1567407781.0...,A famous architect thought to be dying calls A...
16,More Cunning Than Man: A Social History of Rat...,Robert Hendrickson,1999,http://images.amazon.com/images/P/1575663937.0...,"This eye-opening, well-researched examination ..."
17,Goodbye to the Buttermilk Sky,Julia Oliver,1994,http://images.amazon.com/images/P/1881320189.0...,
18,The Testament,John Grisham,1999,http://images.amazon.com/images/P/0440234743.0...,
19,Beloved (Plume Contemporary Fiction),Toni Morrison,1994,http://images.amazon.com/images/P/0452264464.0...,
20,Our Dumb Century: The Onion Presents 100 Years...,The Onion,1999,http://images.amazon.com/images/P/0609804618.0...,The satirical Onion presents its take on the e...
21,New Vegetarian: Bold and Beautiful Recipes for...,Celia Brooks Brown,2001,http://images.amazon.com/images/P/1841721522.0...,
22,If I'd Known Then What I Know Now: Why Not Lea...,J. R. Parrish,2003,http://images.amazon.com/images/P/1879384493.0...,Provides advice on ways to succeed in business...
23,Mary-Kate &amp; Ashley Switching Goals (Mary-K...,Mary-Kate &amp; Ashley Olsen,2000,http://images.amazon.com/images/P/0061076031.0...,"Two twins, one better at soccer than the other..."
24,Tell Me This Isn't Happening,Robynn Clairday,1999,http://images.amazon.com/images/P/0439095026.0...,Please note: This is a companion version & not...
25,Flood : Mississippi 1927,Kathleen Duey,1998,http://images.amazon.com/images/P/0689821166.0...,
26,Wild Animus,Rich Shapero,2004,http://images.amazon.com/images/P/0971880107.0...,How far would you go to find yourself? Wild An...
27,Airframe,Michael Crichton,1997,http://images.amazon.com/images/P/0345402871.0...,
28,Timeline,MICHAEL CRICHTON,2000,http://images.amazon.com/images/P/0345417623.0...,Our critically acclaimed smash hit Cartographi...
29,OUT OF THE SILENT PLANET,C.S. Lewis,1996,http://images.amazon.com/images/P/0684823802.0...,"In ""Out of the Silent Planet,"" C. S. Lewis emb..."
30,Prague : A Novel,ARTHUR PHILLIPS,2003,http://images.amazon.com/images/P/0375759778.0...,"A novel of startling scope and ambition, Pragu..."
31,Chocolate Jesus,Stephan Jaramillo,1998,http://images.amazon.com/images/P/0425163091.0...,
32,Wie Barney es sieht.,Mordecai Richler,2002,http://images.amazon.com/images/P/3404921038.0...,
33,Der Fluch der Kaiserin. Ein Richter- Di- Roman.,Eleanor Cooney,2001,http://images.amazon.com/images/P/3442353866.0...,Im China des Jahres 671 gelingt Richter Di die...
34,Sturmzeit. Roman.,Charlotte Link,1991,http://images.amazon.com/images/P/3442410665.0...,
35,Tage der Unschuld.,Richard North Patterson,2000,http://images.amazon.com/images/P/3442446937.0...,
36,Lying Awake,Mark Salzman,2000,http://images.amazon.com/images/P/0375406328.0...,In a Carmelite monastery outside present-day L...
37,To Kill a Mockingbird,Harper Lee,1988,http://images.amazon.com/images/P/0446310786.0...,Harper Lee's classic novel of a lawyer in the ...
38,Seabiscuit: An American Legend,LAURA HILLENBRAND,2002,http://images.amazon.com/images/P/0449005615.0...,
39,Pigs in Heaven,Barbara Kingsolver,1993,http://images.amazon.com/images/P/0060168013.0...,
40,Miss Zukas and the Raven's Dance,Jo Dereske,1996,http://images.amazon.com/images/P/038078243X.0...,Murder victim Stanley Plummer has been catalog...
41,Pride and Prejudice,Jane Austen,1983,http://images.amazon.com/images/P/055321215X.0...,Austen's comedy of manners--one of the most po...
42,The Therapeutic Touch: How to Use Your Hands t...,Dolores Krieger,1979,http://images.amazon.com/images/P/067176537X.0...,
43,Downtown,Anne Rivers Siddons,1995,http://images.amazon.com/images/P/0061099686.0...,"Mais où nous emmène l’auteur ? Dans ses rêves,..."
44,Icebound,Dean R. Koontz,2000,http://images.amazon.com/images/P/0553582909.0...,
45,I'll Be Seeing You,Mary Higgins Clark,1994,http://images.amazon.com/images/P/0671888587.0...,
46,From the Corner of His Eye,Dean Koontz,2001,http://images.amazon.com/images/P/0553582747.0...,#1 NEW YORK TIMES BESTSELLER • A thrilling and...
47,Isle of Dogs,Patricia Cornwell,2002,http://images.amazon.com/images/P/0425182908.0...,"""English translation of a Japanese adaptation ..."
48,Purity in Death,J.D. Robb,2002,http://images.amazon.com/images/P/042518630X.0...,
49,This Year It Will Be Different: And Other Stories,Maeve Binchy,1997,http://images.amazon.com/images/P/0440223571.0...,Filled with Maeve Binchy's trademark wit and t...